### ISSUE TITLE
[PE-D][Tester E] Adding duplicate persons when not all compulsory fields are filled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-3/tp#199]
Checks for clashes in phone number, email or tele handles work perfectly. A minor nitpick but if a user adds the same person twice, one with only their telegram handle and one only with their phone number, it could result in a duplicate entry. 

eg. At one point user uses command:
add n/Nicole Lee ct/work h/@nicole_lee m/CS2103T r/likes coding t/friend

and then on a separate occasion:
add n/Nicole Lee ct/work p/98765432 m/CS2103T r/likes coding t/friend

![Screenshot 2024-11-08 at 4.26.25 PM.png](https://raw.githubusercontent.com/ryenl/ped/main/files/b153aca4-7670-4962-bc61-4b20dea960aa.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ryenl/ped#1

**Comment by kimberlytmq** [comment]
Not really a bug as people can have the same name but different contact details.
