### ISSUE TITLE
[PE-D][Tester E] Changing to light mode when already in light mode

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W12-3/tp#202]
Very minor nitpick but running the command `switch light` when already in light mode in not highlighted in the ui response. Maybe a response like "App is already using light mode" would be more appropriate

![Screenshot 2024-11-08 at 4.33.29 PM.png](https://raw.githubusercontent.com/ryenl/ped/main/files/748f9b07-9551-4046-a88f-3f824e5e837a.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ryenl/ped#2

**Comment by SlothyCat** [comment]
This is more of an enhancement as it reflects the actual behaviour of the application which is to change to light mode (this is still possible even when you are already in light mode). As checking for an existing theme will require improving the feature, it is not possible to be fixed in v1.5.
