### ISSUE TITLE
[PE-D][Tester D] Comic Sans Font of Contact Type does not fit target audience

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-3/tp#205]
### Describe the Bug
Contact type is shown using Comic Sans font, which may not be appropriate to students looking to use this for a more professional academic/work experience.

### Corresponding Screenshot

![Screenshot 2024-11-08 at 4.38.51 PM.png](https://raw.githubusercontent.com/jayjay19630/ped/main/files/aa11ffc1-809d-4e76-a6a5-a9a4a64ef3e2.png)

### Possible Solutions
Developers should consider using a more standard font such as Times New Roman or Arial.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jayjay19630/ped#3

**Comment by SlothyCat** [comment]
While Comic Sans font is not a standard font like Times New Romand or Arial, it is not considered a bug in our application.
