### ISSUE TITLE
[PE-D][Tester D] Leaving optional fields blank results in empty space in person'

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-3/tp#229]
### Describe the Bug
Add a person with no optional fields results in the person's row having blank spaces, resulting it in looking out of place. This could be unappealing to certain students looking to use this GUI for an academic or work environment

### Corresponding Screenshot

![Screenshot 2024-11-08 at 5.18.47 PM.png](https://raw.githubusercontent.com/jayjay19630/ped/main/files/d52ef22d-5bd7-43c9-87be-b9478fc9b05d.png)

### Possible Solutions
Developers can consider reducing the height of the person row if some optional fields are left blank. Another solution could be to add labels for data fields, but display their values at `None`. So for example, if module was blank, then `Module: None` could be displayed.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jayjay19630/ped#7

**Comment by SlothyCat** [comment]
This bug has been noted and will be solved in future implementations. For now, it will be mentioned in the Developer's Guide for future improvements.
